
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.4.33213.308
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dockerfile", "Dockerfile\Dockerfile.csproj", "{543F4434-4EA5-4360-A3F9-A2B84C1A74A8}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{543F4434-4EA5-4360-A3F9-A2B84C1A74A8}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{543F4434-4EA5-4360-A3F9-A2B84C1A74A8}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{543F4434-4EA5-4360-A3F9-A2B84C1A74A8}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{543F4434-4EA5-4360-A3F9-A2B84C1A74A8}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {FE94BD69-A9F3-47B5-B590-7276BB9E85D5}
	EndGlobalSection
EndGlobal
